/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPayslipsRouteImport } from './routes/_authenticated/payslips'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedHireRequestRouteImport } from './routes/_authenticated/hire-request'
import { Route as AuthenticatedEmployeeTransferRequestRouteImport } from './routes/_authenticated/employee-transfer-request'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayslipsRoute = AuthenticatedPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHireRequestRoute =
  AuthenticatedHireRequestRouteImport.update({
    id: '/hire-request',
    path: '/hire-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeTransferRequestRoute =
  AuthenticatedEmployeeTransferRequestRouteImport.update({
    id: '/employee-transfer-request',
    path: '/employee-transfer-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/employee-transfer-request': typeof AuthenticatedEmployeeTransferRequestRoute
  '/hire-request': typeof AuthenticatedHireRequestRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/payslips': typeof AuthenticatedPayslipsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof PublicLoginRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/employee-transfer-request': typeof AuthenticatedEmployeeTransferRequestRoute
  '/hire-request': typeof AuthenticatedHireRequestRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/payslips': typeof AuthenticatedPayslipsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof PublicLoginRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/employee-transfer-request': typeof AuthenticatedEmployeeTransferRequestRoute
  '/_authenticated/hire-request': typeof AuthenticatedHireRequestRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/payslips': typeof AuthenticatedPayslipsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/attendance'
    | '/employee-transfer-request'
    | '/hire-request'
    | '/leaves'
    | '/payslips'
    | '/profile'
    | '/login'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attendance'
    | '/employee-transfer-request'
    | '/hire-request'
    | '/leaves'
    | '/payslips'
    | '/profile'
    | '/login'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/attendance'
    | '/_authenticated/employee-transfer-request'
    | '/_authenticated/hire-request'
    | '/_authenticated/leaves'
    | '/_authenticated/payslips'
    | '/_authenticated/profile'
    | '/_public/login'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payslips': {
      id: '/_authenticated/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AuthenticatedPayslipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hire-request': {
      id: '/_authenticated/hire-request'
      path: '/hire-request'
      fullPath: '/hire-request'
      preLoaderRoute: typeof AuthenticatedHireRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee-transfer-request': {
      id: '/_authenticated/employee-transfer-request'
      path: '/employee-transfer-request'
      fullPath: '/employee-transfer-request'
      preLoaderRoute: typeof AuthenticatedEmployeeTransferRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedEmployeeTransferRequestRoute: typeof AuthenticatedEmployeeTransferRequestRoute
  AuthenticatedHireRequestRoute: typeof AuthenticatedHireRequestRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedPayslipsRoute: typeof AuthenticatedPayslipsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedEmployeeTransferRequestRoute:
    AuthenticatedEmployeeTransferRequestRoute,
  AuthenticatedHireRequestRoute: AuthenticatedHireRequestRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedPayslipsRoute: AuthenticatedPayslipsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
